runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: lxml
  version: 3.7.3
- name: MySQLdb
  version: 1.2.5

handlers:
- url: .*
  script: main.app

env_variables:
    CLOUDSQL_CONNECTION_NAME: gold-chess-91413:us-central1:gcpcron
    CLOUDSQL_DSN: mysql:unix_socket=/cloudsql/gold-chess-91413:us-central1:gcpcron;dbname=cityjobs
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: sai2903!

